name: Deploy to GitHub Pages

on:
  # Executa em pushes para a branch principal
  push:
    branches: [ "main", "master" ]
  # Permite executar esse workflow manualmente a partir da aba Actions no GitHub
  workflow_dispatch:

# Define as permissões do token GITHUB_TOKEN para a ação
permissions:
  contents: read
  pages: write
  id-token: write

# Permite somente um deploy simultâneo
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: 'npm'
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Install dependencies
        run: npm ci
      - name: Generate content
        run: npm run setup
      - name: Build with Astro
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./docs

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2